name: FancyTrails
main: net.zyrkcraft.fancytrails.Plugin
description: Gives your players the ability to look cool!
version: 0.7.2
author: ZyrkRan

commands:
  fancytrails:
    description: Open the trails GUI 
    aliases: [ft, t]
    
